ALTER TABLE page_heads ADD COLUMN IF NOT EXISTS position TEXT NULL;
ALTER TABLE page_heads ADD COLUMN IF NOT EXISTS icon TEXT NULL;

ALTER TABLE page_versions ADD COLUMN IF NOT EXISTS position TEXT NULL;
ALTER TABLE page_versions ADD COLUMN IF NOT EXISTS icon TEXT NULL;
